### ISSUE TITLE
v2版无法构建镜像

### ISSUE THREAD

**Issue by HebeDich** [wisdgod/pieces-os-go#1]
也无法拉取到新镜像..

**Comment by wisdgod** [comment]
pkg/tokenizer/claude.go
pkg/tokenizer/num.go
go.mod
go.sum
这些文件换成v1的，这是一个临时的解决方案，下一次更新这些问题都会解决（如果服务可用的话）

有个依赖换了，要GCC的，还要一个静态库

之前的不知道为什么隔一段时间就会报错

看错误信息像是V1依赖的bug（在上下文长时，也可能是资源不足）
